# Generated by Django 5.2.17 on 2026-09-03 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Project title', max_length=200)),
                ('short_description', models.CharField(blank=True, default='', help_text='Brief tagline or summary', max_length=300)),
                ('description', models.TextField(help_text='Detailed project requirements, goal, and architecture')),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold')], default='planning', max_length=20)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=20)),
                ('cover_image', models.URLField(blank=True, default='', help_text='Optional cover image URL', max_length=500)),
                ('github_url', models.URLField(blank=True, default='', max_length=255)),
                ('demo_url', models.URLField(blank=True, default='', max_length=255)),
                ('owner', models.ForeignKey(help_text='Project creator / owner', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
                ('skills', models.ManyToManyField(blank=True, related_name='projects', to='users.skill')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
