# Generated by Django 5.2.17 on 2026-09-03 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('COLLABORATION_REQUEST', 'Collaboration Request'), ('COLLABORATION_ACCEPTED', 'Collaboration Accepted'), ('COLLABORATION_REJECTED', 'Collaboration Rejected'), ('MEMBER_REMOVED', 'Member Removed'), ('MEMBER_LEFT', 'Member Left')], max_length=50)),
                ('message', models.TextField(help_text='Generated notification text')),
                ('is_read', models.BooleanField(default=False, help_text='Read status')),
                ('actor', models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acted_notifications', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(help_text='User receiving the notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='notif_recip_read_created_idx')],
            },
        ),
    ]
