# Generated by Django 5.2.17 on 2026-09-03 14:51

import django.contrib.auth.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(help_text='Required. Primary email address for login.', max_length=254, unique=True)),
                ('username', models.CharField(help_text='Required. Unique username handle.', max_length=150, unique=True)),
                ('avatar', models.URLField(blank=True, default='', help_text='URL to avatar image.', max_length=500)),
                ('bio', models.TextField(blank=True, default='', help_text='Short developer bio/description.')),
                ('location', models.CharField(blank=True, default='', help_text='City, Country or Remote.', max_length=100)),
                ('job_title', models.CharField(blank=True, default='', help_text='e.g. Full Stack Engineer, Frontend Developer.', max_length=100)),
                ('experience_level', models.CharField(blank=True, choices=[('entry', 'Entry Level (0-2 yrs)'), ('mid', 'Mid Level (2-5 yrs)'), ('senior', 'Senior (5-8 yrs)'), ('lead', 'Lead / Staff (8+ yrs)'), ('principal', 'Principal / Architect')], default='mid', max_length=20)),
                ('preferred_role', models.CharField(blank=True, default='', help_text='e.g. Backend Developer, UI/UX Designer.', max_length=100)),
                ('availability', models.CharField(choices=[('available', 'Available for Projects'), ('busy', 'Busy / Limited Availability'), ('not_available', 'Not Available')], default='available', max_length=20)),
                ('github_url', models.URLField(blank=True, default='', max_length=255)),
                ('linkedin_url', models.URLField(blank=True, default='', max_length=255)),
                ('portfolio_url', models.URLField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('skills', models.ManyToManyField(blank=True, related_name='users', to='users.skill')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
